/**
 * index.ts — ArfheWallet agent proxy.
 *
 * POST /agent/chat forwards the extension's in-wallet agent requests to OpenRouter. Exists so
 * the OpenRouter API key never ships inside the extension bundle (anyone could unpack a Chrome
 * extension and read it); the key lives only as a Cloudflare Worker secret
 * (`wrangler secret put OPENROUTER_API_KEY`), never in this repo or in a `.env` file read at
 * runtime.
 *
 * Request:  { messages: ChatMessage[], tools?: ToolDefinition[] }
 * Response: the raw OpenRouter chat-completion JSON, status forwarded as-is once a model
 *           in MODEL_CHAIN answers with something other than 429/5xx.
 *
 * POST /agent/retrieve-context — RAG context lookup, see handleRetrieveContext below.
 *
 * POST /agent/x402/payment-required, POST /agent/x402/settle — Faz 3's x402 micro-payments.
 * Stub (x402Stub.ts) by default; env.X402_USE_REAL_FACILITATOR = "true" switches both to the
 * real facilitator client (x402FacilitatorClient.ts). Neither talks to a real resource server —
 * there isn't one — payment-required is always generated by this Worker itself; only
 * verify/settle talk to something real (the public x402 facilitator) when the flag is on.
 *
 * POST /users/register, POST /activity/log — pseudonymous wallet/activity tracking against
 * the USERS_DB D1 database (see migrations/0001_create_users_activity.sql). No amount/value
 * is ever accepted or stored by either endpoint — only that a send/shield/unshield happened,
 * never how much, so this never contradicts the FHE-shielded-balance architecture with a
 * plaintext amount log.
 *
 * GET /admin/users, GET /admin/activity — read-only dumps of the above, gated by
 * `Authorization: Bearer <ADMIN_SECRET>` (Worker secret, see README) instead of the
 * extension-origin CORS check, since these are called by an operator, not the extension.
 */

import { MODEL_CHAIN } from "./modelConfig";
import { checkRateLimit } from "./rateLimiter";
import { retrieveContext } from "./knowledge/retrieveContext";
import { buildStubPaymentRequirements, buildStubSettlement } from "./x402Stub";
import { buildRealPaymentRequiredBody, settleX402PaymentReal } from "./x402FacilitatorClient";

export interface Env {
  /** Cloudflare Worker secret — set via `wrangler secret put OPENROUTER_API_KEY`, never a var. */
  OPENROUTER_API_KEY: string;
  /** Exact `chrome-extension://<id>` origin allowed to call this proxy. Set in wrangler.toml [vars]. */
  ALLOWED_ORIGIN: string;
  /** Exact arfhewallet.dev origin allowed to call GET /api/tasks and GET /api/user-tasks/:x_user_id via CORS. Set in wrangler.toml [vars]. */
  SITE_ORIGIN?: string;
  /** Requests allowed per IP per 60s. Optional; defaults to 20 if unset/unparseable. */
  RATE_LIMIT_PER_MINUTE?: string;
  RATE_LIMIT_KV: KVNamespace;
  /** Workers AI binding, used only to embed the query for RAG context retrieval. */
  AI: Ai;
  /** "true" routes /agent/x402/* through x402FacilitatorClient.ts (real facilitator) instead of x402Stub.ts. Set in wrangler.toml [vars]; defaults to stub when unset. */
  X402_USE_REAL_FACILITATOR?: string;
  /** Base Sepolia address that receives real x402 settlements. Required only when X402_USE_REAL_FACILITATOR is "true". Set in wrangler.toml [vars]. */
  X402_PAYTO_ADDRESS?: string;
  /** Base Sepolia USDC contract address. Required only when X402_USE_REAL_FACILITATOR is "true". Set in wrangler.toml [vars]. */
  X402_USDC_ASSET_ADDRESS?: string;
  /** Facilitator base URL override. Optional; defaults to https://x402.org/facilitator (see x402FacilitatorClient.ts). */
  X402_FACILITATOR_URL?: string;
  /** D1 database binding for pseudonymous wallet/activity tracking. See migrations/0001_create_users_activity.sql. */
  USERS_DB: D1Database;
  /** Cloudflare Worker secret — set via `wrangler secret put ADMIN_SECRET`, never a var. Gates GET /admin/*. */
  ADMIN_SECRET?: string;
  /**
   * Cloudflare Worker secret — set via `wrangler secret put INTERNAL_API_SECRET`, never a var.
   * Shared secret the arfhewallet.dev site sends as `X-Internal-Secret` on POST /api/x-login
   * and POST /api/user-tasks, so only our own site's backend (not an arbitrary browser) can
   * create x_users rows or submit task completions. See isAuthorizedInternal.
   */
  INTERNAL_API_SECRET?: string;
  /**
   * Cloudflare Worker secret — set via `wrangler secret put HUNT_REWARD_SEED`, never a var.
   * The reward payload handed back by POST /api/reveal-reward once a user's hunt submission is
   * approved. Not yet provisioned; add it before /api/reveal-reward is used in production.
   */
  HUNT_REWARD_SEED?: string;
  /**
   * Cloudflare Worker secret — set via `wrangler secret put HUNT_ADMIN_SECRET`, never a var.
   * Gates POST /api/admin/hunt/review and GET /api/admin/hunt/pending. Deliberately a separate
   * secret from ADMIN_SECRET: hunt reward review is a distinct operator role from the general
   * /admin/* dashboard. See isAuthorizedHuntAdmin.
   */
  HUNT_ADMIN_SECRET?: string;
}

const OPENROUTER_ENDPOINT = "https://openrouter.ai/api/v1/chat/completions";
const UPSTREAM_TIMEOUT_MS = 30_000;
const DEFAULT_RATE_LIMIT_PER_MINUTE = 20;

interface ChatMessage {
  role: "system" | "user" | "assistant" | "tool";
  content: string;
  [key: string]: unknown;
}

interface ToolDefinition {
  type: "function";
  function: {
    name: string;
    description?: string;
    parameters?: Record<string, unknown>;
  };
}

interface AgentChatRequestBody {
  messages: ChatMessage[];
  tools?: ToolDefinition[];
}

// ─── Small helpers ──────────────────────────────────────────────────

function jsonResponse(body: unknown, status: number, extraHeaders?: HeadersInit): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "Content-Type": "application/json", ...extraHeaders },
  });
}

/** Only a request whose Origin exactly matches the configured extension origin gets CORS headers. */
function buildCorsHeaders(origin: string | null, env: Env): HeadersInit | null {
  if (!origin || !env.ALLOWED_ORIGIN || origin !== env.ALLOWED_ORIGIN) return null;
  return {
    "Access-Control-Allow-Origin": origin,
    "Access-Control-Allow-Methods": "POST, OPTIONS",
    "Access-Control-Allow-Headers": "Content-Type",
    Vary: "Origin",
  };
}

/**
 * Same pattern as buildCorsHeaders, but for the arfhewallet.dev site's own origin rather than
 * the extension's — gates the two public, browser-facing GET routes (GET /api/tasks, GET
 * /api/user-tasks/:x_user_id). GET-only: unlike the extension's POST-only surface, nothing
 * behind this CORS check ever mutates data, so there's no method to allow beyond GET/OPTIONS.
 * POST /api/x-login and POST /api/user-tasks are deliberately NOT covered by this — they're
 * called server-to-server (the site's Vercel backend, with X-Internal-Secret), never from a
 * browser, so they carry no CORS headers at all.
 */
function buildSiteCorsHeaders(origin: string | null, env: Env): HeadersInit | null {
  if (!origin || !env.SITE_ORIGIN) return null;
  const bareOrigin = env.SITE_ORIGIN.replace("https://www.", "https://");
  const allowedOrigins = new Set([bareOrigin, bareOrigin.replace("https://", "https://www.")]);
  if (!allowedOrigins.has(origin)) return null;
  return {
    "Access-Control-Allow-Origin": origin,
    "Access-Control-Allow-Methods": "GET, OPTIONS",
    "Access-Control-Allow-Headers": "Content-Type",
    Vary: "Origin",
  };
}

function isChatMessage(value: unknown): value is ChatMessage {
  if (typeof value !== "object" || value === null) return false;
  const v = value as Record<string, unknown>;
  return (
    (v.role === "system" || v.role === "user" || v.role === "assistant" || v.role === "tool") &&
    typeof v.content === "string"
  );
}

function parseRequestBody(raw: unknown): AgentChatRequestBody {
  if (typeof raw !== "object" || raw === null) {
    throw new Error("Request body must be a JSON object.");
  }
  const body = raw as Record<string, unknown>;

  if (!Array.isArray(body.messages) || body.messages.length === 0 || !body.messages.every(isChatMessage)) {
    throw new Error('"messages" must be a non-empty array of { role, content } items.');
  }

  if (body.tools !== undefined && !Array.isArray(body.tools)) {
    throw new Error('"tools", when present, must be an array.');
  }

  return {
    messages: body.messages,
    tools: body.tools as ToolDefinition[] | undefined,
  };
}

// ─── Model chain ────────────────────────────────────────────────────

type ChainResult =
  | { kind: "response"; status: number; data: unknown }
  | { kind: "all_rate_limited"; attemptedModels: string[] }
  | { kind: "unreachable"; attemptedModels: string[] };

/**
 * Try each model in MODEL_CHAIN until one answers with something other than 429 (rate
 * limited), 5xx (upstream outage), 404 (model no longer exists in OpenRouter's catalog —
 * free-tier models get retired without notice, which is exactly what happened to
 * qwen/qwen3-coder:free), or a "successful" status whose body isn't valid JSON (a model/
 * provider-side glitch, not a real answer — logged with the offending model name and a
 * truncated body sample). Those are the only cases worth falling back for — anything else
 * (auth failure, malformed request, a genuine completion) is returned as-is, since retrying
 * a different model wouldn't change a client-side error and would just mask a real answer.
 */
async function callModelChain(body: AgentChatRequestBody, apiKey: string): Promise<ChainResult> {
  let sawRateLimit = false;
  let sawUnreachable = false;
  // Recorded so a caller-visible "all failed" error can say exactly which models were tried,
  // instead of leaving it ambiguous whether the chain was exhausted or aborted after one.
  const attemptedModels: string[] = [];

  for (const model of MODEL_CHAIN) {
    attemptedModels.push(model);
    let response: Response;
    try {
      response = await fetch(OPENROUTER_ENDPOINT, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${apiKey}`,
          "HTTP-Referer": "https://arfhewallet.app",
          "X-Title": "ArfheWallet Agent",
        },
        body: JSON.stringify({
          model,
          messages: body.messages,
          ...(body.tools ? { tools: body.tools } : {}),
        }),
        signal: AbortSignal.timeout(UPSTREAM_TIMEOUT_MS),
      });
    } catch {
      // Network error or timeout reaching OpenRouter itself — try the next model.
      sawUnreachable = true;
      continue;
    }

    if (response.status === 429) {
      sawRateLimit = true;
      continue;
    }
    if (response.status === 404 || response.status >= 500) {
      // Covers 502/503/504 (e.g. a provider-side "ResourceExhausted") exactly like a 5xx,
      // and 404 for a model retired from OpenRouter's catalog — neither is a mistake in our
      // own request, so both fall through to the next model instead of being returned as-is.
      sawUnreachable = true;
      continue;
    }

    // A "successful" status (not 429/404/5xx) with a body that isn't valid JSON is never a
    // usable completion — it's a model/provider-side glitch (an HTML error page, truncated
    // output, etc.), not a real answer. Treated as retryable exactly like 5xx/429, rather
    // than forwarded as a synthetic {error} "response" that would short-circuit the whole
    // fallback chain on one flaky model. The raw body (truncated) and which model produced
    // it are logged so a future occurrence is diagnosable from `wrangler tail` / dev console
    // instead of only showing up as the client's generic "couldn't process that" reply.
    const rawText = await response.text();
    let data: unknown;
    try {
      data = JSON.parse(rawText);
    } catch {
      console.error(
        `[agent-proxy] model "${model}" returned status ${response.status} with a non-JSON body:`,
        rawText.slice(0, 500)
      );
      sawUnreachable = true;
      continue;
    }

    return { kind: "response", status: response.status, data };
  }

  if (sawUnreachable) return { kind: "unreachable", attemptedModels };
  if (sawRateLimit) return { kind: "all_rate_limited", attemptedModels };
  // MODEL_CHAIN is a non-empty const array, so this is unreachable in practice.
  return { kind: "unreachable", attemptedModels };
}

// ─── RAG context retrieval ──────────────────────────────────────────

interface RetrieveContextRequestBody {
  query: string;
}

function parseRetrieveContextBody(raw: unknown): RetrieveContextRequestBody {
  if (typeof raw !== "object" || raw === null || typeof (raw as { query?: unknown }).query !== "string") {
    throw new Error('"query" must be a string.');
  }
  return { query: (raw as { query: string }).query };
}

/**
 * Embeds the caller's message and returns the RAG chunks worth splicing into the agent's
 * context — read-only enrichment, never a source of new tool-call authority (see
 * AgentPolicyEngine on the extension side, which this endpoint never touches). Any
 * retrieval failure degrades to an empty chunk list with a 200, not an error status —
 * AgentOrchestrator treats "no context available" as a normal outcome, not a chat failure.
 */
async function handleRetrieveContext(request: Request, env: Env, cors: HeadersInit): Promise<Response> {
  let body: RetrieveContextRequestBody;
  try {
    body = parseRetrieveContextBody(await request.json());
  } catch (err) {
    return jsonResponse({ error: err instanceof Error ? err.message : "Invalid request body." }, 400, cors);
  }

  const scoredChunks = await retrieveContext(env.AI, body.query);
  return jsonResponse(
    { chunks: scoredChunks.map((s) => ({ title: s.chunk.title, text: s.chunk.text, score: s.score })) },
    200,
    cors
  );
}

// ─── x402 (Faz 3) ─────────────────────────────────────────────────
//
// Two routes, each with a stub path (x402Stub.ts) and a real path (x402FacilitatorClient.ts),
// selected per-request by env.X402_USE_REAL_FACILITATOR ("true" = real, anything else = stub —
// stub is the default so existing deployments/tests keep working unless explicitly opted in).
// The stub is NOT deleted: it stays available as a fallback for local dev/testing without
// touching the real (free, public, but still third-party) facilitator. See x402FacilitatorClient.ts's
// own JSDoc for the real facilitator's request/response shapes, verified live while building this.

interface X402PaymentRequiredRequestBody {
  resource: string;
}

function parseX402PaymentRequiredBody(raw: unknown): X402PaymentRequiredRequestBody {
  if (typeof raw !== "object" || raw === null || typeof (raw as { resource?: unknown }).resource !== "string" || !(raw as { resource: string }).resource.trim()) {
    throw new Error('"resource" must be a non-empty string.');
  }
  return { resource: (raw as { resource: string }).resource };
}

/**
 * Real path: builds a genuine v1 PaymentRequirements body (payTo/asset from env — see
 * x402FacilitatorClient.ts). Stub path (default): x402Stub.ts's canned data.
 */
async function handleX402PaymentRequired(request: Request, env: Env, cors: HeadersInit): Promise<Response> {
  let body: X402PaymentRequiredRequestBody;
  try {
    body = parseX402PaymentRequiredBody(await request.json());
  } catch (err) {
    return jsonResponse({ error: err instanceof Error ? err.message : "Invalid request body." }, 400, cors);
  }

  if (env.X402_USE_REAL_FACILITATOR === "true") {
    try {
      return jsonResponse(buildRealPaymentRequiredBody(body.resource, env), 402, cors);
    } catch (err) {
      return jsonResponse({ error: err instanceof Error ? err.message : "x402 yapılandırma hatası." }, 500, cors);
    }
  }

  return jsonResponse(buildStubPaymentRequirements(body.resource), 402, cors);
}

interface X402SettleRequestBody {
  resource: string;
  paymentPayload: unknown;
}

function parseX402SettleBody(raw: unknown): X402SettleRequestBody {
  if (typeof raw !== "object" || raw === null) {
    throw new Error("Request body must be a JSON object.");
  }
  const body = raw as Record<string, unknown>;
  if (typeof body.resource !== "string" || !body.resource.trim()) {
    throw new Error('"resource" must be a non-empty string.');
  }
  if (!("paymentPayload" in body)) {
    throw new Error('"paymentPayload" is required.');
  }
  return { resource: body.resource, paymentPayload: body.paymentPayload };
}

/**
 * Real path: verifies then settles with the real facilitator (x402FacilitatorClient.ts),
 * translates its `transaction` field to `txHash` so X402ProxyClient.ts's contract on the
 * extension side never has to change, and maps a facilitator-side failure (bad signature,
 * expired authorization, etc.) to a 402 with `{ error: <raw facilitator reason> }`.
 * X402ProxyClient.settleX402Payment() reads that `error` field on any non-2xx response and
 * throws it verbatim (falling back to a generic status-code message only when the body isn't
 * JSON or has no `error` string) — UserFacingError.ts's x402 matchers then turn that raw reason
 * into a user-appropriate message instead of a generic "try again".
 * Stub path (default): x402Stub.ts's canned, always-succeeds data.
 */
async function handleX402Settle(request: Request, env: Env, cors: HeadersInit): Promise<Response> {
  let body: X402SettleRequestBody;
  try {
    body = parseX402SettleBody(await request.json());
  } catch (err) {
    return jsonResponse({ error: err instanceof Error ? err.message : "Invalid request body." }, 400, cors);
  }

  if (env.X402_USE_REAL_FACILITATOR === "true") {
    let result;
    try {
      result = await settleX402PaymentReal(body.resource, body.paymentPayload, env);
    } catch (err) {
      return jsonResponse({ error: err instanceof Error ? err.message : "x402 facilitator hatası." }, 502, cors);
    }
    if (!result.success) {
      return jsonResponse({ error: result.error }, 402, cors);
    }
    return jsonResponse({ success: true, txHash: result.txHash, network: result.network }, 200, cors);
  }

  return jsonResponse(buildStubSettlement(body.resource), 200, cors);
}

// ─── Users / activity tracking ──────────────────────────────────────
//
// Pseudonymous by design, not anonymous: wallet_address is a public on-chain identifier.
// What is deliberately never accepted or stored here is an amount — action_type only
// records that a send/shield/unshield happened, never how much, so this table can't leak
// the FHE-shielded balances the rest of the wallet exists to protect.

const USER_SOURCES = ["google", "created", "mnemonic", "private_key"] as const;
type UserSource = (typeof USER_SOURCES)[number];

interface UsersRegisterRequestBody {
  wallet_address: string;
  source: UserSource;
}

function parseUsersRegisterBody(raw: unknown): UsersRegisterRequestBody {
  if (typeof raw !== "object" || raw === null) {
    throw new Error("Request body must be a JSON object.");
  }
  const body = raw as Record<string, unknown>;

  if (typeof body.wallet_address !== "string" || !body.wallet_address.trim()) {
    throw new Error('"wallet_address" must be a non-empty string.');
  }
  if (typeof body.source !== "string" || !USER_SOURCES.includes(body.source as UserSource)) {
    throw new Error(`"source" must be one of: ${USER_SOURCES.join(", ")}.`);
  }

  return {
    wallet_address: body.wallet_address,
    source: body.source as UserSource,
  };
}

/**
 * Upserts one row into `users`. `first_seen` and `source` are only ever written on the
 * initial insert (the `ON CONFLICT` clause never touches them); `last_seen` is bumped on
 * every call.
 */
async function handleUsersRegister(request: Request, env: Env, cors: HeadersInit): Promise<Response> {
  let body: UsersRegisterRequestBody;
  try {
    body = parseUsersRegisterBody(await request.json());
  } catch (err) {
    return jsonResponse({ error: err instanceof Error ? err.message : "Invalid request body." }, 400, cors);
  }

  const now = new Date().toISOString();
  await env.USERS_DB.prepare(
    `INSERT INTO users (wallet_address, source, first_seen, last_seen)
     VALUES (?1, ?2, ?3, ?3)
     ON CONFLICT(wallet_address) DO UPDATE SET
       last_seen = ?3`
  )
    .bind(body.wallet_address, body.source, now)
    .run();

  return jsonResponse({ ok: true }, 200, cors);
}

interface ActivityLogRequestBody {
  wallet_address: string;
  action_type: "send" | "shield" | "unshield";
}

function parseActivityLogBody(raw: unknown): ActivityLogRequestBody {
  if (typeof raw !== "object" || raw === null) {
    throw new Error("Request body must be a JSON object.");
  }
  const body = raw as Record<string, unknown>;

  if (typeof body.wallet_address !== "string" || !body.wallet_address.trim()) {
    throw new Error('"wallet_address" must be a non-empty string.');
  }
  if (body.action_type !== "send" && body.action_type !== "shield" && body.action_type !== "unshield") {
    throw new Error('"action_type" must be "send", "shield", or "unshield".');
  }

  return { wallet_address: body.wallet_address, action_type: body.action_type };
}

/** Inserts one row into `activity`. Every call is a new row — there is no upsert here. */
async function handleActivityLog(request: Request, env: Env, cors: HeadersInit): Promise<Response> {
  let body: ActivityLogRequestBody;
  try {
    body = parseActivityLogBody(await request.json());
  } catch (err) {
    return jsonResponse({ error: err instanceof Error ? err.message : "Invalid request body." }, 400, cors);
  }

  const now = new Date().toISOString();
  await env.USERS_DB.prepare(`INSERT INTO activity (wallet_address, action_type, timestamp) VALUES (?1, ?2, ?3)`)
    .bind(body.wallet_address, body.action_type, now)
    .run();

  return jsonResponse({ ok: true }, 200, cors);
}

// ─── X (Twitter) login + task tracking ───────────────────────────────
//
// arfhewallet.dev site backend calls these — not the wallet extension — so they are gated by
// a shared secret (X-Internal-Secret) instead of the extension-origin CORS check, and are not
// subject to the extension's per-IP rate limiter. See migrations/0004_create_x_tasks.sql.

const USER_TASK_STATUSES = ["pending", "approved", "rejected"] as const;
type UserTaskStatus = (typeof USER_TASK_STATUSES)[number];

interface XUserRow {
  id: number;
  x_username: string;
  x_user_id: string;
  created_at: string;
}

interface TaskRow {
  id: number;
  title: string;
  description: string | null;
  active: number;
  created_at: string;
}

/**
 * `X-Internal-Secret: <INTERNAL_API_SECRET>` gate for POST /api/x-login and POST
 * /api/user-tasks. Deliberately a distinct secret from ADMIN_SECRET: this one is held by the
 * site's own backend (a server-to-server call), not typed in by a human operator.
 */
function isAuthorizedInternal(request: Request, env: Env): boolean {
  if (!env.INTERNAL_API_SECRET) return false;
  return request.headers.get("X-Internal-Secret") === env.INTERNAL_API_SECRET;
}

interface XLoginRequestBody {
  x_username: string;
  x_user_id: string;
}

function parseXLoginBody(raw: unknown): XLoginRequestBody {
  if (typeof raw !== "object" || raw === null) {
    throw new Error("Request body must be a JSON object.");
  }
  const body = raw as Record<string, unknown>;

  if (typeof body.x_username !== "string" || !body.x_username.trim()) {
    throw new Error('"x_username" must be a non-empty string.');
  }
  if (typeof body.x_user_id !== "string" || !body.x_user_id.trim()) {
    throw new Error('"x_user_id" must be a non-empty string.');
  }

  return { x_username: body.x_username, x_user_id: body.x_user_id };
}

/**
 * Looks up x_users by x_user_id (X's immutable id, not the mutable username) and inserts a
 * row on first sight. `ON CONFLICT(x_user_id) DO NOTHING` makes this race-safe: two concurrent
 * logins from the same X account never produce two rows or a thrown error. A UNIQUE violation
 * can still surface if x_username collides across two *different* x_user_id values — treated
 * as a 409 rather than a 500 since it's a legitimate (if rare) data conflict, not a bug.
 */
async function handleXLogin(request: Request, env: Env, cors: HeadersInit | undefined): Promise<Response> {
  let body: XLoginRequestBody;
  try {
    body = parseXLoginBody(await request.json());
  } catch (err) {
    return jsonResponse({ error: err instanceof Error ? err.message : "Invalid request body." }, 400, cors);
  }

  const now = new Date().toISOString();
  try {
    await env.USERS_DB.prepare(
      `INSERT INTO x_users (x_username, x_user_id, created_at)
       VALUES (?1, ?2, ?3)
       ON CONFLICT(x_user_id) DO NOTHING`
    )
      .bind(body.x_username, body.x_user_id, now)
      .run();
  } catch (err) {
    return jsonResponse(
      { error: "x_username is already associated with a different X account." },
      409,
      cors
    );
  }

  const row = await env.USERS_DB.prepare(
    `SELECT id, x_username, x_user_id, created_at FROM x_users WHERE x_user_id = ?1`
  )
    .bind(body.x_user_id)
    .first<XUserRow>();

  return jsonResponse(row, 200, cors);
}

/** GET /api/tasks — public, no secret: the active task list is what the site shows every visitor. */
async function handleTasksList(env: Env, cors: HeadersInit | undefined): Promise<Response> {
  const { results } = await env.USERS_DB.prepare(
    `SELECT id, title, description, active, created_at FROM tasks WHERE active = 1 ORDER BY created_at ASC`
  ).all<TaskRow>();
  return jsonResponse(results ?? [], 200, cors);
}

interface UserTaskSubmitRequestBody {
  x_user_id: string;
  task_id: number;
}

function parseUserTaskSubmitBody(raw: unknown): UserTaskSubmitRequestBody {
  if (typeof raw !== "object" || raw === null) {
    throw new Error("Request body must be a JSON object.");
  }
  const body = raw as Record<string, unknown>;

  if (typeof body.x_user_id !== "string" || !body.x_user_id.trim()) {
    throw new Error('"x_user_id" must be a non-empty string.');
  }
  if (typeof body.task_id !== "number" || !Number.isInteger(body.task_id)) {
    throw new Error('"task_id" must be an integer.');
  }

  return { x_user_id: body.x_user_id, task_id: body.task_id };
}

/**
 * Inserts one 'pending' user_tasks row. The (user_id, task_id) UNIQUE constraint (see
 * migrations/0004_create_x_tasks.sql) is what actually enforces "submit once" — this handler
 * just translates that constraint violation into a 409 instead of a raw D1 error.
 */
async function handleUserTaskSubmit(request: Request, env: Env, cors: HeadersInit | undefined): Promise<Response> {
  let body: UserTaskSubmitRequestBody;
  try {
    body = parseUserTaskSubmitBody(await request.json());
  } catch (err) {
    return jsonResponse({ error: err instanceof Error ? err.message : "Invalid request body." }, 400, cors);
  }

  const user = await env.USERS_DB.prepare(`SELECT id FROM x_users WHERE x_user_id = ?1`)
    .bind(body.x_user_id)
    .first<{ id: number }>();
  if (!user) {
    return jsonResponse({ error: "Unknown x_user_id. Call /api/x-login first." }, 404, cors);
  }

  const task = await env.USERS_DB.prepare(`SELECT id FROM tasks WHERE id = ?1`)
    .bind(body.task_id)
    .first<{ id: number }>();
  if (!task) {
    return jsonResponse({ error: "Unknown task_id." }, 404, cors);
  }

  const now = new Date().toISOString();
  try {
    await env.USERS_DB.prepare(
      `INSERT INTO user_tasks (user_id, task_id, status, submitted_at) VALUES (?1, ?2, 'pending', ?3)`
    )
      .bind(user.id, body.task_id, now)
      .run();
  } catch (err) {
    return jsonResponse({ error: "This task has already been submitted." }, 409, cors);
  }

  return jsonResponse({ ok: true }, 200, cors);
}

interface UserTaskSubmissionRow {
  task_id: number;
  title: string;
  status: UserTaskStatus;
  submitted_at: string;
  reviewed_at: string | null;
}

/**
 * GET /api/user-tasks/:x_user_id — public, no secret: a user checking their own submission
 * status isn't a privileged operation (x_user_id is not a secret, same as a public handle).
 * `all_completed` means "submitted to every currently-active task", regardless of
 * approved/rejected/pending — matching the spec literally rather than gating it on approval.
 */
async function handleUserTasksForUser(env: Env, xUserId: string, cors: HeadersInit | undefined): Promise<Response> {
  const user = await env.USERS_DB.prepare(`SELECT id FROM x_users WHERE x_user_id = ?1`)
    .bind(xUserId)
    .first<{ id: number }>();
  if (!user) {
    return jsonResponse({ error: "Unknown x_user_id." }, 404, cors);
  }

  const { results } = await env.USERS_DB.prepare(
    `SELECT ut.task_id AS task_id, t.title AS title, ut.status AS status,
            ut.submitted_at AS submitted_at, ut.reviewed_at AS reviewed_at
     FROM user_tasks ut
     JOIN tasks t ON t.id = ut.task_id
     WHERE ut.user_id = ?1
     ORDER BY ut.submitted_at ASC`
  )
    .bind(user.id)
    .all<UserTaskSubmissionRow>();

  const activeCountRow = await env.USERS_DB.prepare(`SELECT COUNT(*) AS cnt FROM tasks WHERE active = 1`).first<{
    cnt: number;
  }>();
  const submittedActiveCountRow = await env.USERS_DB.prepare(
    `SELECT COUNT(*) AS cnt FROM user_tasks ut JOIN tasks t ON t.id = ut.task_id WHERE ut.user_id = ?1 AND t.active = 1`
  )
    .bind(user.id)
    .first<{ cnt: number }>();

  const activeCount = activeCountRow?.cnt ?? 0;
  const submittedActiveCount = submittedActiveCountRow?.cnt ?? 0;
  const allCompleted = activeCount > 0 && submittedActiveCount >= activeCount;

  return jsonResponse({ submissions: results ?? [], all_completed: allCompleted }, 200, cors);
}

interface HuntCompleteRequestBody {
  x_user_id: string;
}

function parseHuntCompleteBody(raw: unknown): HuntCompleteRequestBody {
  if (typeof raw !== "object" || raw === null) {
    throw new Error("Request body must be a JSON object.");
  }
  const body = raw as Record<string, unknown>;

  if (typeof body.x_user_id !== "string" || !body.x_user_id.trim()) {
    throw new Error('"x_user_id" must be a non-empty string.');
  }

  return { x_user_id: body.x_user_id };
}

/**
 * POST /api/complete-hunt — internal-secret gated. Marks the whole hunt as submitted for a
 * user in one shot, replacing the per-task tracking in `user_tasks` (see
 * migrations/0009_add_hunt_completion.sql). `x_users.status` defaulting to NULL is what
 * makes this one-shot: a second call while status is already set is rejected as a duplicate
 * submission instead of silently resetting a pending/reviewed state.
 */
async function handleCompleteHunt(request: Request, env: Env, cors: HeadersInit | undefined): Promise<Response> {
  let body: HuntCompleteRequestBody;
  try {
    body = parseHuntCompleteBody(await request.json());
  } catch (err) {
    return jsonResponse({ error: err instanceof Error ? err.message : "Invalid request body." }, 400, cors);
  }

  const user = await env.USERS_DB.prepare(`SELECT id, status FROM x_users WHERE x_user_id = ?1`)
    .bind(body.x_user_id)
    .first<{ id: number; status: string | null }>();
  if (!user) {
    return jsonResponse({ error: "Unknown x_user_id. Call /api/x-login first." }, 404, cors);
  }
  if (user.status !== null) {
    return jsonResponse({ error: "Hunt has already been submitted." }, 409, cors);
  }

  const now = new Date().toISOString();
  await env.USERS_DB.prepare(`UPDATE x_users SET status = 'pending', submitted_at = ?1 WHERE id = ?2`)
    .bind(now, user.id)
    .run();

  return jsonResponse({ ok: true }, 200, cors);
}

interface HuntStatusRow {
  status: string | null;
  submitted_at: string | null;
  reviewed_at: string | null;
}

/**
 * GET /api/hunt-status/:x_user_id — public, no secret: same reasoning as
 * GET /api/user-tasks/:x_user_id (x_user_id is not a secret, same as a public handle).
 */
async function handleHuntStatus(env: Env, xUserId: string, cors: HeadersInit | undefined): Promise<Response> {
  const row = await env.USERS_DB.prepare(
    `SELECT status, submitted_at, reviewed_at FROM x_users WHERE x_user_id = ?1`
  )
    .bind(xUserId)
    .first<HuntStatusRow>();
  if (!row) {
    return jsonResponse({ error: "Unknown x_user_id." }, 404, cors);
  }

  return jsonResponse(row, 200, cors);
}

interface HuntReviewRequestBody {
  x_user_id: string;
  action: "approve" | "reject";
}

function parseHuntReviewBody(raw: unknown): HuntReviewRequestBody {
  if (typeof raw !== "object" || raw === null) {
    throw new Error("Request body must be a JSON object.");
  }
  const body = raw as Record<string, unknown>;

  if (typeof body.x_user_id !== "string" || !body.x_user_id.trim()) {
    throw new Error('"x_user_id" must be a non-empty string.');
  }
  if (body.action !== "approve" && body.action !== "reject") {
    throw new Error('"action" must be "approve" or "reject".');
  }

  return { x_user_id: body.x_user_id, action: body.action };
}

/**
 * POST /api/admin/hunt/review — Hunt-Admin-Secret gated (isAuthorizedHuntAdmin), a distinct
 * secret from the general /admin/* routes below. Sets x_users.status to 'approved' or
 * 'rejected' and stamps reviewed_at. Does not require the current status to be 'pending'
 * first: an admin correcting a prior review (e.g. flipping a mistaken reject) is a legitimate
 * use, not a bug.
 */
async function handleAdminHuntReview(request: Request, env: Env): Promise<Response> {
  let body: HuntReviewRequestBody;
  try {
    body = parseHuntReviewBody(await request.json());
  } catch (err) {
    return jsonResponse({ error: err instanceof Error ? err.message : "Invalid request body." }, 400);
  }

  const user = await env.USERS_DB.prepare(`SELECT id FROM x_users WHERE x_user_id = ?1`)
    .bind(body.x_user_id)
    .first<{ id: number }>();
  if (!user) {
    return jsonResponse({ error: "Unknown x_user_id." }, 404);
  }

  const status = body.action === "approve" ? "approved" : "rejected";
  const now = new Date().toISOString();
  await env.USERS_DB.prepare(`UPDATE x_users SET status = ?1, reviewed_at = ?2 WHERE id = ?3`)
    .bind(status, now, user.id)
    .run();

  return jsonResponse({ ok: true }, 200);
}

interface AdminHuntPendingRow {
  x_user_id: string;
  x_username: string;
  submitted_at: string | null;
}

/** GET /api/admin/hunt/pending — Hunt-Admin-Secret gated (isAuthorizedHuntAdmin). Review queue. */
async function handleAdminHuntPending(env: Env): Promise<Response> {
  const { results } = await env.USERS_DB.prepare(
    `SELECT x_user_id, x_username, submitted_at FROM x_users WHERE status = 'pending' ORDER BY submitted_at ASC`
  ).all<AdminHuntPendingRow>();
  return jsonResponse(results ?? [], 200);
}

interface AdminHuntReviewedRow {
  x_user_id: string;
  x_username: string;
  status: string;
  submitted_at: string | null;
  reviewed_at: string | null;
}

/** GET /api/admin/hunt/reviewed — Hunt-Admin-Secret gated (isAuthorizedHuntAdmin). Already-reviewed history. */
async function handleAdminHuntReviewed(env: Env): Promise<Response> {
  const { results } = await env.USERS_DB.prepare(
    `SELECT x_user_id, x_username, status, submitted_at, reviewed_at FROM x_users
     WHERE status = 'approved' OR status = 'rejected'
     ORDER BY reviewed_at DESC`
  ).all<AdminHuntReviewedRow>();
  return jsonResponse(results ?? [], 200);
}

interface RevealRewardRequestBody {
  x_user_id: string;
}

function parseRevealRewardBody(raw: unknown): RevealRewardRequestBody {
  if (typeof raw !== "object" || raw === null) {
    throw new Error("Request body must be a JSON object.");
  }
  const body = raw as Record<string, unknown>;

  if (typeof body.x_user_id !== "string" || !body.x_user_id.trim()) {
    throw new Error('"x_user_id" must be a non-empty string.');
  }

  return { x_user_id: body.x_user_id };
}

/**
 * POST /api/reveal-reward — internal-secret gated, server-to-server ONLY. Deliberately never
 * exposed via buildSiteCorsHeaders/buildCorsHeaders: env.HUNT_REWARD_SEED is the reward
 * payload itself, so a browser-reachable route here would let anyone with an x_user_id read
 * it directly, bypassing the approve/reject gate entirely. Returns { seed: null } (200, not
 * 403) for anyone not yet approved — "no reward available" is not an error condition.
 */
async function handleRevealReward(request: Request, env: Env): Promise<Response> {
  let body: RevealRewardRequestBody;
  try {
    body = parseRevealRewardBody(await request.json());
  } catch (err) {
    return jsonResponse({ error: err instanceof Error ? err.message : "Invalid request body." }, 400);
  }

  const user = await env.USERS_DB.prepare(`SELECT status FROM x_users WHERE x_user_id = ?1`)
    .bind(body.x_user_id)
    .first<{ status: string | null }>();

  if (!user || user.status !== "approved") {
    return jsonResponse({ seed: null }, 200);
  }

  return jsonResponse({ seed: env.HUNT_REWARD_SEED ?? null }, 200);
}

/**
 * `Authorization: Bearer <ADMIN_SECRET>` gate for the /admin/* routes below. Deliberately
 * not the extension-origin CORS check the other routes use — an operator hits these from a
 * terminal or an internal dashboard, not the wallet extension, so there is no browser
 * Origin header to validate against.
 */
function isAuthorizedAdmin(request: Request, env: Env): boolean {
  if (!env.ADMIN_SECRET) return false;
  return request.headers.get("Authorization") === `Bearer ${env.ADMIN_SECRET}`;
}

/**
 * `Hunt-Admin-Secret: <HUNT_ADMIN_SECRET>` gate for POST /api/admin/hunt/review and GET
 * /api/admin/hunt/pending. Parallel to isAuthorizedAdmin above but deliberately a distinct
 * secret and header: hunt reward review is a separate operator role from the general
 * /admin/* dashboard, so the two can be rotated/granted independently.
 */
function isAuthorizedHuntAdmin(request: Request, env: Env): boolean {
  if (!env.HUNT_ADMIN_SECRET) return false;
  return request.headers.get("Hunt-Admin-Secret") === env.HUNT_ADMIN_SECRET;
}

async function handleAdminUsers(env: Env): Promise<Response> {
  const { results } = await env.USERS_DB.prepare(
    `SELECT wallet_address, source, first_seen, last_seen FROM users ORDER BY last_seen DESC`
  ).all();
  return jsonResponse(results ?? [], 200);
}

async function handleAdminActivity(env: Env): Promise<Response> {
  const { results } = await env.USERS_DB.prepare(
    `SELECT id, wallet_address, action_type, timestamp FROM activity ORDER BY wallet_address ASC, timestamp DESC`
  ).all();
  return jsonResponse(results ?? [], 200);
}

// ─── Admin dashboard (static HTML/JS shell) ─────────────────────────
//
// GET /admin is intentionally public with no server-side auth: the page itself carries no
// data, only a login form. The secret the operator types is kept in sessionStorage (never
// localStorage — gone the moment the tab closes) and sent as `Authorization: Bearer` on
// same-origin fetches to /admin/users and /admin/activity, which ARE gated by
// isAuthorizedAdmin above. A wrong secret gets a 401 from those, not from this page.

const ADMIN_PAGE_HTML = `<!DOCTYPE html>
<html lang="tr">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>ArfheWallet Admin</title>
<style>
  :root { color-scheme: light dark; }
  * { box-sizing: border-box; }
  body {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
    margin: 0;
    padding: 24px;
    background: #0f172a;
    color: #e2e8f0;
  }
  h1 { font-size: 18px; font-weight: 700; margin: 0 0 16px; }
  #loginBox {
    max-width: 360px;
    margin: 80px auto;
    padding: 24px;
    background: #1e293b;
    border: 1px solid #334155;
    border-radius: 8px;
  }
  #loginBox label { display: block; font-size: 13px; margin-bottom: 6px; color: #94a3b8; }
  #loginBox input {
    width: 100%;
    padding: 8px 10px;
    background: #0f172a;
    border: 1px solid #334155;
    border-radius: 4px;
    color: #e2e8f0;
    font-size: 14px;
    margin-bottom: 12px;
  }
  button {
    padding: 8px 16px;
    background: #2563eb;
    color: white;
    border: none;
    border-radius: 4px;
    font-size: 14px;
    cursor: pointer;
  }
  button:hover { background: #1d4ed8; }
  #error { color: #f87171; font-size: 13px; margin-top: 8px; min-height: 16px; }
  #app { display: none; }
  .tabs { display: flex; gap: 8px; margin-bottom: 16px; }
  .tab {
    padding: 6px 14px;
    background: #1e293b;
    border: 1px solid #334155;
    border-radius: 4px;
    cursor: pointer;
    font-size: 13px;
    color: #94a3b8;
  }
  .tab.active { background: #2563eb; color: white; border-color: #2563eb; }
  #search {
    width: 100%;
    max-width: 400px;
    padding: 8px 10px;
    background: #1e293b;
    border: 1px solid #334155;
    border-radius: 4px;
    color: #e2e8f0;
    font-size: 14px;
    margin-bottom: 16px;
  }
  table { border-collapse: collapse; width: 100%; font-size: 13px; }
  th, td {
    text-align: left;
    padding: 8px 10px;
    border-bottom: 1px solid #334155;
    white-space: nowrap;
  }
  th { cursor: pointer; color: #94a3b8; user-select: none; }
  th:hover { color: #e2e8f0; }
  th .arrow { font-size: 10px; margin-left: 4px; }
  tbody tr:hover { background: #1e293b; }
  .empty { color: #64748b; padding: 16px 0; font-size: 13px; }
  .panel { display: none; }
  .panel.active { display: block; }
  .logout { margin-left: 12px; background: #334155; }
  .logout:hover { background: #475569; }
</style>
</head>
<body>

<div id="loginBox">
  <h1>ArfheWallet Admin</h1>
  <label for="secretInput">Admin secret</label>
  <input id="secretInput" type="password" autocomplete="off" />
  <button id="loginBtn">Giriş</button>
  <div id="error"></div>
</div>

<div id="app">
  <h1>ArfheWallet Admin <button class="logout" id="logoutBtn">Çıkış</button></h1>
  <div class="tabs">
    <div class="tab active" data-panel="users">Kullanıcılar</div>
    <div class="tab" data-panel="activity">Aktivite</div>
  </div>
  <input id="search" type="text" placeholder="wallet_address içinde ara..." />

  <div class="panel active" id="panel-users">
    <table>
      <thead>
        <tr>
          <th data-key="wallet_address">wallet_address<span class="arrow"></span></th>
          <th data-key="source">source<span class="arrow"></span></th>
          <th data-key="first_seen">first_seen<span class="arrow"></span></th>
          <th data-key="last_seen">last_seen<span class="arrow"></span></th>
        </tr>
      </thead>
      <tbody id="usersBody"></tbody>
    </table>
    <div class="empty" id="usersEmpty" style="display:none;">Kayıt yok.</div>
  </div>

  <div class="panel" id="panel-activity">
    <table>
      <thead>
        <tr>
          <th data-key="wallet_address">wallet_address<span class="arrow"></span></th>
          <th data-key="action_type">action_type<span class="arrow"></span></th>
          <th data-key="timestamp">timestamp<span class="arrow"></span></th>
        </tr>
      </thead>
      <tbody id="activityBody"></tbody>
    </table>
    <div class="empty" id="activityEmpty" style="display:none;">Kayıt yok.</div>
  </div>
</div>

<script>
(function () {
  "use strict";

  var STORAGE_KEY = "arfhe_admin_secret";
  var usersData = [];
  var activityData = [];
  var activeTab = "users";
  var sortState = { users: { key: null, dir: 1 }, activity: { key: null, dir: 1 } };

  var loginBox = document.getElementById("loginBox");
  var app = document.getElementById("app");
  var secretInput = document.getElementById("secretInput");
  var loginBtn = document.getElementById("loginBtn");
  var logoutBtn = document.getElementById("logoutBtn");
  var errorEl = document.getElementById("error");
  var searchEl = document.getElementById("search");
  var tabs = document.querySelectorAll(".tab");

  function escapeHtml(value) {
    return String(value == null ? "" : value).replace(/[&<>"']/g, function (c) {
      return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c];
    });
  }

  function getSecret() {
    return sessionStorage.getItem(STORAGE_KEY);
  }

  function setSecret(value) {
    sessionStorage.setItem(STORAGE_KEY, value);
  }

  function clearSecret() {
    sessionStorage.removeItem(STORAGE_KEY);
  }

  async function fetchAdmin(path) {
    var secret = getSecret();
    var res = await fetch(path, {
      headers: { Authorization: "Bearer " + secret },
    });
    if (res.status === 401) {
      var err = new Error("unauthorized");
      err.isAuth = true;
      throw err;
    }
    if (!res.ok) {
      throw new Error("request failed: " + res.status);
    }
    return res.json();
  }

  async function loadData() {
    var results = await Promise.all([fetchAdmin("/admin/users"), fetchAdmin("/admin/activity")]);
    usersData = results[0] || [];
    activityData = results[1] || [];
    render();
  }

  function showApp() {
    loginBox.style.display = "none";
    app.style.display = "block";
  }

  function showLogin(message) {
    app.style.display = "none";
    loginBox.style.display = "block";
    errorEl.textContent = message || "";
  }

  function matchesSearch(row, query) {
    if (!query) return true;
    var q = query.toLowerCase();
    var addr = (row.wallet_address || "").toLowerCase();
    return addr.indexOf(q) !== -1;
  }

  function sortRows(rows, key, dir) {
    if (!key) return rows;
    var copy = rows.slice();
    copy.sort(function (a, b) {
      var av = a[key] == null ? "" : a[key];
      var bv = b[key] == null ? "" : b[key];
      if (av < bv) return -1 * dir;
      if (av > bv) return 1 * dir;
      return 0;
    });
    return copy;
  }

  function renderTable(tbodyId, emptyId, rows, columns) {
    var tbody = document.getElementById(tbodyId);
    var empty = document.getElementById(emptyId);
    if (rows.length === 0) {
      tbody.innerHTML = "";
      empty.style.display = "block";
      return;
    }
    empty.style.display = "none";
    var html = "";
    for (var i = 0; i < rows.length; i++) {
      html += "<tr>";
      for (var c = 0; c < columns.length; c++) {
        html += "<td>" + escapeHtml(rows[i][columns[c]]) + "</td>";
      }
      html += "</tr>";
    }
    tbody.innerHTML = html;
  }

  function updateSortArrows(panelKey) {
    var ths = document.querySelectorAll("#panel-" + panelKey + " th");
    ths.forEach(function (th) {
      var arrow = th.querySelector(".arrow");
      if (th.getAttribute("data-key") === sortState[panelKey].key) {
        arrow.textContent = sortState[panelKey].dir === 1 ? "▲" : "▼";
      } else {
        arrow.textContent = "";
      }
    });
  }

  function render() {
    var query = searchEl.value.trim();

    var filteredUsers = usersData.filter(function (r) { return matchesSearch(r, query); });
    filteredUsers = sortRows(filteredUsers, sortState.users.key, sortState.users.dir);
    renderTable("usersBody", "usersEmpty", filteredUsers, ["wallet_address", "source", "first_seen", "last_seen"]);
    updateSortArrows("users");

    var filteredActivity = activityData.filter(function (r) { return matchesSearch(r, query); });
    filteredActivity = sortRows(filteredActivity, sortState.activity.key, sortState.activity.dir);
    renderTable("activityBody", "activityEmpty", filteredActivity, ["wallet_address", "action_type", "timestamp"]);
    updateSortArrows("activity");
  }

  async function attemptLogin(secret) {
    setSecret(secret);
    try {
      await loadData();
      showApp();
    } catch (e) {
      clearSecret();
      if (e && e.isAuth) {
        showLogin("Secret hatalı.");
      } else {
        showLogin("Sunucuya erişilemedi, tekrar deneyin.");
      }
    }
  }

  loginBtn.addEventListener("click", function () {
    var value = secretInput.value.trim();
    if (!value) return;
    attemptLogin(value);
  });

  secretInput.addEventListener("keydown", function (e) {
    if (e.key === "Enter") loginBtn.click();
  });

  logoutBtn.addEventListener("click", function () {
    clearSecret();
    secretInput.value = "";
    showLogin("");
  });

  searchEl.addEventListener("input", render);

  tabs.forEach(function (tab) {
    tab.addEventListener("click", function () {
      tabs.forEach(function (t) { t.classList.remove("active"); });
      tab.classList.add("active");
      activeTab = tab.getAttribute("data-panel");
      document.querySelectorAll(".panel").forEach(function (p) { p.classList.remove("active"); });
      document.getElementById("panel-" + activeTab).classList.add("active");
    });
  });

  document.querySelectorAll("th[data-key]").forEach(function (th) {
    th.addEventListener("click", function () {
      var panelKey = th.closest(".panel").id.replace("panel-", "");
      var key = th.getAttribute("data-key");
      var state = sortState[panelKey];
      if (state.key === key) {
        state.dir = -state.dir;
      } else {
        state.key = key;
        state.dir = 1;
      }
      render();
    });
  });

  // Auto-login if a secret from earlier this tab session is still around.
  var existing = getSecret();
  if (existing) {
    attemptLogin(existing);
  }
})();
</script>
</body>
</html>`;

function handleAdminPage(): Response {
  return new Response(ADMIN_PAGE_HTML, {
    status: 200,
    headers: { "Content-Type": "text/html; charset=utf-8" },
  });
}

// ─── Worker entrypoint ──────────────────────────────────────────────

const KNOWN_PATHS = new Set([
  "/agent/chat",
  "/agent/retrieve-context",
  "/agent/x402/payment-required",
  "/agent/x402/settle",
  "/users/register",
  "/activity/log",
]);

const ADMIN_PATHS = new Set(["/admin/users", "/admin/activity"]);

// GET /api/tasks and GET /api/user-tasks/:x_user_id — the only two routes gated by
// buildSiteCorsHeaders instead of buildCorsHeaders. Shared by the OPTIONS preflight branch and
// the route dispatch below so the two can't drift out of sync.
const USER_TASKS_GET_PATTERN = /^\/api\/user-tasks\/[^/]+$/;
const HUNT_STATUS_GET_PATTERN = /^\/api\/hunt-status\/[^/]+$/;
function isSiteCorsPath(pathname: string): boolean {
  return (
    pathname === "/api/tasks" ||
    USER_TASKS_GET_PATTERN.test(pathname) ||
    HUNT_STATUS_GET_PATTERN.test(pathname)
  );
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);
    const origin = request.headers.get("Origin");
    const cors = buildCorsHeaders(origin, env);

    if (request.method === "OPTIONS") {
      if (isSiteCorsPath(url.pathname)) {
        const siteCors = buildSiteCorsHeaders(origin, env);
        return new Response(null, { status: siteCors ? 204 : 403, headers: siteCors ?? undefined });
      }
      // Preflight from a disallowed origin gets no CORS headers, so the browser blocks the
      // actual request itself — no need to leak a distinct error body here.
      return new Response(null, { status: cors ? 204 : 403, headers: cors ?? undefined });
    }

    // Admin dashboard shell: intentionally public, no server-side auth — see the comment
    // above ADMIN_PAGE_HTML. Checked before the Bearer-gated /admin/* data routes below.
    if (url.pathname === "/admin" && request.method === "GET") {
      return handleAdminPage();
    }

    // X login / task routes: shared-secret or public per-route, not origin/CORS gated or
    // rate-limited — see the "X (Twitter) login + task tracking" section above.
    if (url.pathname === "/api/x-login" && request.method === "POST") {
      if (!isAuthorizedInternal(request, env)) {
        return jsonResponse({ error: "Unauthorized." }, 401);
      }
      return handleXLogin(request, env, undefined);
    }

    if (url.pathname === "/api/tasks" && request.method === "GET") {
      return handleTasksList(env, buildSiteCorsHeaders(origin, env) ?? undefined);
    }

    if (url.pathname === "/api/user-tasks" && request.method === "POST") {
      if (!isAuthorizedInternal(request, env)) {
        return jsonResponse({ error: "Unauthorized." }, 401);
      }
      return handleUserTaskSubmit(request, env, undefined);
    }

    const userTasksMatch = url.pathname.match(/^\/api\/user-tasks\/([^/]+)$/);
    if (userTasksMatch && userTasksMatch[1] && request.method === "GET") {
      return handleUserTasksForUser(
        env,
        decodeURIComponent(userTasksMatch[1]),
        buildSiteCorsHeaders(origin, env) ?? undefined
      );
    }

    // Simplified hunt completion (see migrations/0009_simplify_user_completion.sql): replaces
    // per-task submission with a single "I did it" flag stored directly on x_users.
    if (url.pathname === "/api/complete-hunt" && request.method === "POST") {
      if (!isAuthorizedInternal(request, env)) {
        return jsonResponse({ error: "Unauthorized." }, 401);
      }
      return handleCompleteHunt(request, env, undefined);
    }

    const huntStatusMatch = url.pathname.match(/^\/api\/hunt-status\/([^/]+)$/);
    if (huntStatusMatch && huntStatusMatch[1] && request.method === "GET") {
      return handleHuntStatus(
        env,
        decodeURIComponent(huntStatusMatch[1]),
        buildSiteCorsHeaders(origin, env) ?? undefined
      );
    }

    // Admin routes: Bearer-token gated, not origin/CORS gated — see isAuthorizedAdmin.
    if (ADMIN_PATHS.has(url.pathname)) {
      if (request.method !== "GET") {
        return jsonResponse({ error: "Method not allowed." }, 405);
      }
      if (!isAuthorizedAdmin(request, env)) {
        return jsonResponse({ error: "Unauthorized." }, 401);
      }
      return url.pathname === "/admin/users" ? handleAdminUsers(env) : handleAdminActivity(env);
    }

    // Hunt reward review + reveal. Hunt-admin-secret (distinct from ADMIN_SECRET) or
    // internal-secret gated, never origin/CORS gated — see isAuthorizedHuntAdmin /
    // isAuthorizedInternal above.
    if (url.pathname === "/api/admin/hunt/review" && request.method === "POST") {
      if (!isAuthorizedHuntAdmin(request, env)) {
        return jsonResponse({ error: "Unauthorized." }, 401);
      }
      return handleAdminHuntReview(request, env);
    }

    if (url.pathname === "/api/admin/hunt/pending" && request.method === "GET") {
      if (!isAuthorizedHuntAdmin(request, env)) {
        return jsonResponse({ error: "Unauthorized." }, 401);
      }
      return handleAdminHuntPending(env);
    }

    if (url.pathname === "/api/admin/hunt/reviewed" && request.method === "GET") {
      if (!isAuthorizedHuntAdmin(request, env)) {
        return jsonResponse({ error: "Unauthorized." }, 401);
      }
      return handleAdminHuntReviewed(env);
    }

    // Deliberately absent from isSiteCorsPath/USER_TASKS_GET_PATTERN-style CORS allowlisting:
    // this is server-to-server only (see handleRevealReward).
    if (url.pathname === "/api/reveal-reward" && request.method === "POST") {
      if (!isAuthorizedInternal(request, env)) {
        return jsonResponse({ error: "Unauthorized." }, 401);
      }
      return handleRevealReward(request, env);
    }

    if (request.method !== "POST" || !KNOWN_PATHS.has(url.pathname)) {
      return jsonResponse({ error: "Not found." }, 404, cors ?? undefined);
    }

    if (!cors) {
      return jsonResponse({ error: "Origin not allowed." }, 403);
    }

    const clientIp = request.headers.get("CF-Connecting-IP") ?? "unknown";
    const limitPerMinute = Number.parseInt(env.RATE_LIMIT_PER_MINUTE ?? "", 10) || DEFAULT_RATE_LIMIT_PER_MINUTE;
    const rate = await checkRateLimit(env.RATE_LIMIT_KV, clientIp, limitPerMinute);
    if (!rate.allowed) {
      return jsonResponse(
        { error: "Rate limit exceeded. Try again shortly." },
        429,
        { ...cors, "Retry-After": String(rate.retryAfterSeconds ?? 60) }
      );
    }

    if (url.pathname === "/agent/retrieve-context") {
      return handleRetrieveContext(request, env, cors);
    }

    if (url.pathname === "/agent/x402/payment-required") {
      return handleX402PaymentRequired(request, env, cors);
    }

    if (url.pathname === "/agent/x402/settle") {
      return handleX402Settle(request, env, cors);
    }

    if (url.pathname === "/users/register") {
      return handleUsersRegister(request, env, cors);
    }

    if (url.pathname === "/activity/log") {
      return handleActivityLog(request, env, cors);
    }

    if (!env.OPENROUTER_API_KEY) {
      return jsonResponse({ error: "Server misconfigured: missing OPENROUTER_API_KEY." }, 500, cors);
    }

    let body: AgentChatRequestBody;
    try {
      body = parseRequestBody(await request.json());
    } catch (err) {
      return jsonResponse({ error: err instanceof Error ? err.message : "Invalid request body." }, 400, cors);
    }

    const result = await callModelChain(body, env.OPENROUTER_API_KEY);

    switch (result.kind) {
      case "response":
        return jsonResponse(result.data, result.status, cors);
      case "all_rate_limited":
        return jsonResponse(
          {
            error: "All models in the fallback chain are currently rate limited. Try again shortly.",
            attemptedModels: result.attemptedModels,
          },
          503,
          cors
        );
      case "unreachable":
        return jsonResponse(
          {
            error: "OpenRouter is unreachable, or none of the configured models are currently available.",
            attemptedModels: result.attemptedModels,
          },
          502,
          cors
        );
    }
  },
};
