/**
 * index.ts — ArfheWallet agent proxy.
 *
 * POST /agent/chat forwards the extension's in-wallet agent requests to OpenRouter. Exists so
 * the OpenRouter API key never ships inside the extension bundle (anyone could unpack a Chrome
 * extension and read it); the key lives only as a Cloudflare Worker secret
 * (`wrangler secret put OPENROUTER_API_KEY`), never in this repo or in a `.env` file read at
 * runtime.
 *
 * Request:  { messages: ChatMessage[], tools?: ToolDefinition[] }
 * Response: the raw OpenRouter chat-completion JSON, status forwarded as-is once a model
 *           in MODEL_CHAIN answers with something other than 429/5xx.
 *
 * POST /agent/retrieve-context — RAG context lookup, see handleRetrieveContext below.
 *
 * POST /agent/x402/payment-required, POST /agent/x402/settle — Faz 3's x402 micro-payments.
 * Stub (x402Stub.ts) by default; env.X402_USE_REAL_FACILITATOR = "true" switches both to the
 * real facilitator client (x402FacilitatorClient.ts). Neither talks to a real resource server —
 * there isn't one — payment-required is always generated by this Worker itself; only
 * verify/settle talk to something real (the public x402 facilitator) when the flag is on.
 */

import { MODEL_CHAIN } from "./modelConfig";
import { checkRateLimit } from "./rateLimiter";
import { retrieveContext } from "./knowledge/retrieveContext";
import { buildStubPaymentRequirements, buildStubSettlement } from "./x402Stub";
import { buildRealPaymentRequiredBody, settleX402PaymentReal } from "./x402FacilitatorClient";

export interface Env {
  /** Cloudflare Worker secret — set via `wrangler secret put OPENROUTER_API_KEY`, never a var. */
  OPENROUTER_API_KEY: string;
  /** Exact `chrome-extension://<id>` origin allowed to call this proxy. Set in wrangler.toml [vars]. */
  ALLOWED_ORIGIN: string;
  /** Requests allowed per IP per 60s. Optional; defaults to 20 if unset/unparseable. */
  RATE_LIMIT_PER_MINUTE?: string;
  RATE_LIMIT_KV: KVNamespace;
  /** Workers AI binding, used only to embed the query for RAG context retrieval. */
  AI: Ai;
  /** "true" routes /agent/x402/* through x402FacilitatorClient.ts (real facilitator) instead of x402Stub.ts. Set in wrangler.toml [vars]; defaults to stub when unset. */
  X402_USE_REAL_FACILITATOR?: string;
  /** Base Sepolia address that receives real x402 settlements. Required only when X402_USE_REAL_FACILITATOR is "true". Set in wrangler.toml [vars]. */
  X402_PAYTO_ADDRESS?: string;
  /** Base Sepolia USDC contract address. Required only when X402_USE_REAL_FACILITATOR is "true". Set in wrangler.toml [vars]. */
  X402_USDC_ASSET_ADDRESS?: string;
  /** Facilitator base URL override. Optional; defaults to https://x402.org/facilitator (see x402FacilitatorClient.ts). */
  X402_FACILITATOR_URL?: string;
}

const OPENROUTER_ENDPOINT = "https://openrouter.ai/api/v1/chat/completions";
const UPSTREAM_TIMEOUT_MS = 30_000;
const DEFAULT_RATE_LIMIT_PER_MINUTE = 20;

interface ChatMessage {
  role: "system" | "user" | "assistant" | "tool";
  content: string;
  [key: string]: unknown;
}

interface ToolDefinition {
  type: "function";
  function: {
    name: string;
    description?: string;
    parameters?: Record<string, unknown>;
  };
}

interface AgentChatRequestBody {
  messages: ChatMessage[];
  tools?: ToolDefinition[];
}

// ─── Small helpers ──────────────────────────────────────────────────

function jsonResponse(body: unknown, status: number, extraHeaders?: HeadersInit): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "Content-Type": "application/json", ...extraHeaders },
  });
}

/** Only a request whose Origin exactly matches the configured extension origin gets CORS headers. */
function buildCorsHeaders(origin: string | null, env: Env): HeadersInit | null {
  if (!origin || !env.ALLOWED_ORIGIN || origin !== env.ALLOWED_ORIGIN) return null;
  return {
    "Access-Control-Allow-Origin": origin,
    "Access-Control-Allow-Methods": "POST, OPTIONS",
    "Access-Control-Allow-Headers": "Content-Type",
    Vary: "Origin",
  };
}

function isChatMessage(value: unknown): value is ChatMessage {
  if (typeof value !== "object" || value === null) return false;
  const v = value as Record<string, unknown>;
  return (
    (v.role === "system" || v.role === "user" || v.role === "assistant" || v.role === "tool") &&
    typeof v.content === "string"
  );
}

function parseRequestBody(raw: unknown): AgentChatRequestBody {
  if (typeof raw !== "object" || raw === null) {
    throw new Error("Request body must be a JSON object.");
  }
  const body = raw as Record<string, unknown>;

  if (!Array.isArray(body.messages) || body.messages.length === 0 || !body.messages.every(isChatMessage)) {
    throw new Error('"messages" must be a non-empty array of { role, content } items.');
  }

  if (body.tools !== undefined && !Array.isArray(body.tools)) {
    throw new Error('"tools", when present, must be an array.');
  }

  return {
    messages: body.messages,
    tools: body.tools as ToolDefinition[] | undefined,
  };
}

// ─── Model chain ────────────────────────────────────────────────────

type ChainResult =
  | { kind: "response"; status: number; data: unknown }
  | { kind: "all_rate_limited"; attemptedModels: string[] }
  | { kind: "unreachable"; attemptedModels: string[] };

/**
 * Try each model in MODEL_CHAIN until one answers with something other than 429 (rate
 * limited), 5xx (upstream outage), 404 (model no longer exists in OpenRouter's catalog —
 * free-tier models get retired without notice, which is exactly what happened to
 * qwen/qwen3-coder:free), or a "successful" status whose body isn't valid JSON (a model/
 * provider-side glitch, not a real answer — logged with the offending model name and a
 * truncated body sample). Those are the only cases worth falling back for — anything else
 * (auth failure, malformed request, a genuine completion) is returned as-is, since retrying
 * a different model wouldn't change a client-side error and would just mask a real answer.
 */
async function callModelChain(body: AgentChatRequestBody, apiKey: string): Promise<ChainResult> {
  let sawRateLimit = false;
  let sawUnreachable = false;
  // Recorded so a caller-visible "all failed" error can say exactly which models were tried,
  // instead of leaving it ambiguous whether the chain was exhausted or aborted after one.
  const attemptedModels: string[] = [];

  for (const model of MODEL_CHAIN) {
    attemptedModels.push(model);
    let response: Response;
    try {
      response = await fetch(OPENROUTER_ENDPOINT, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${apiKey}`,
          "HTTP-Referer": "https://arfhewallet.app",
          "X-Title": "ArfheWallet Agent",
        },
        body: JSON.stringify({
          model,
          messages: body.messages,
          ...(body.tools ? { tools: body.tools } : {}),
        }),
        signal: AbortSignal.timeout(UPSTREAM_TIMEOUT_MS),
      });
    } catch {
      // Network error or timeout reaching OpenRouter itself — try the next model.
      sawUnreachable = true;
      continue;
    }

    if (response.status === 429) {
      sawRateLimit = true;
      continue;
    }
    if (response.status === 404 || response.status >= 500) {
      // Covers 502/503/504 (e.g. a provider-side "ResourceExhausted") exactly like a 5xx,
      // and 404 for a model retired from OpenRouter's catalog — neither is a mistake in our
      // own request, so both fall through to the next model instead of being returned as-is.
      sawUnreachable = true;
      continue;
    }

    // A "successful" status (not 429/404/5xx) with a body that isn't valid JSON is never a
    // usable completion — it's a model/provider-side glitch (an HTML error page, truncated
    // output, etc.), not a real answer. Treated as retryable exactly like 5xx/429, rather
    // than forwarded as a synthetic {error} "response" that would short-circuit the whole
    // fallback chain on one flaky model. The raw body (truncated) and which model produced
    // it are logged so a future occurrence is diagnosable from `wrangler tail` / dev console
    // instead of only showing up as the client's generic "couldn't process that" reply.
    const rawText = await response.text();
    let data: unknown;
    try {
      data = JSON.parse(rawText);
    } catch {
      console.error(
        `[agent-proxy] model "${model}" returned status ${response.status} with a non-JSON body:`,
        rawText.slice(0, 500)
      );
      sawUnreachable = true;
      continue;
    }

    return { kind: "response", status: response.status, data };
  }

  if (sawUnreachable) return { kind: "unreachable", attemptedModels };
  if (sawRateLimit) return { kind: "all_rate_limited", attemptedModels };
  // MODEL_CHAIN is a non-empty const array, so this is unreachable in practice.
  return { kind: "unreachable", attemptedModels };
}

// ─── RAG context retrieval ──────────────────────────────────────────

interface RetrieveContextRequestBody {
  query: string;
}

function parseRetrieveContextBody(raw: unknown): RetrieveContextRequestBody {
  if (typeof raw !== "object" || raw === null || typeof (raw as { query?: unknown }).query !== "string") {
    throw new Error('"query" must be a string.');
  }
  return { query: (raw as { query: string }).query };
}

/**
 * Embeds the caller's message and returns the RAG chunks worth splicing into the agent's
 * context — read-only enrichment, never a source of new tool-call authority (see
 * AgentPolicyEngine on the extension side, which this endpoint never touches). Any
 * retrieval failure degrades to an empty chunk list with a 200, not an error status —
 * AgentOrchestrator treats "no context available" as a normal outcome, not a chat failure.
 */
async function handleRetrieveContext(request: Request, env: Env, cors: HeadersInit): Promise<Response> {
  let body: RetrieveContextRequestBody;
  try {
    body = parseRetrieveContextBody(await request.json());
  } catch (err) {
    return jsonResponse({ error: err instanceof Error ? err.message : "Invalid request body." }, 400, cors);
  }

  const scoredChunks = await retrieveContext(env.AI, body.query);
  return jsonResponse(
    { chunks: scoredChunks.map((s) => ({ title: s.chunk.title, text: s.chunk.text, score: s.score })) },
    200,
    cors
  );
}

// ─── x402 (Faz 3) ─────────────────────────────────────────────────
//
// Two routes, each with a stub path (x402Stub.ts) and a real path (x402FacilitatorClient.ts),
// selected per-request by env.X402_USE_REAL_FACILITATOR ("true" = real, anything else = stub —
// stub is the default so existing deployments/tests keep working unless explicitly opted in).
// The stub is NOT deleted: it stays available as a fallback for local dev/testing without
// touching the real (free, public, but still third-party) facilitator. See x402FacilitatorClient.ts's
// own JSDoc for the real facilitator's request/response shapes, verified live while building this.

interface X402PaymentRequiredRequestBody {
  resource: string;
}

function parseX402PaymentRequiredBody(raw: unknown): X402PaymentRequiredRequestBody {
  if (typeof raw !== "object" || raw === null || typeof (raw as { resource?: unknown }).resource !== "string" || !(raw as { resource: string }).resource.trim()) {
    throw new Error('"resource" must be a non-empty string.');
  }
  return { resource: (raw as { resource: string }).resource };
}

/**
 * Real path: builds a genuine v1 PaymentRequirements body (payTo/asset from env — see
 * x402FacilitatorClient.ts). Stub path (default): x402Stub.ts's canned data.
 */
async function handleX402PaymentRequired(request: Request, env: Env, cors: HeadersInit): Promise<Response> {
  let body: X402PaymentRequiredRequestBody;
  try {
    body = parseX402PaymentRequiredBody(await request.json());
  } catch (err) {
    return jsonResponse({ error: err instanceof Error ? err.message : "Invalid request body." }, 400, cors);
  }

  if (env.X402_USE_REAL_FACILITATOR === "true") {
    try {
      return jsonResponse(buildRealPaymentRequiredBody(body.resource, env), 402, cors);
    } catch (err) {
      return jsonResponse({ error: err instanceof Error ? err.message : "x402 yapılandırma hatası." }, 500, cors);
    }
  }

  return jsonResponse(buildStubPaymentRequirements(body.resource), 402, cors);
}

interface X402SettleRequestBody {
  resource: string;
  paymentPayload: unknown;
}

function parseX402SettleBody(raw: unknown): X402SettleRequestBody {
  if (typeof raw !== "object" || raw === null) {
    throw new Error("Request body must be a JSON object.");
  }
  const body = raw as Record<string, unknown>;
  if (typeof body.resource !== "string" || !body.resource.trim()) {
    throw new Error('"resource" must be a non-empty string.');
  }
  if (!("paymentPayload" in body)) {
    throw new Error('"paymentPayload" is required.');
  }
  return { resource: body.resource, paymentPayload: body.paymentPayload };
}

/**
 * Real path: verifies then settles with the real facilitator (x402FacilitatorClient.ts),
 * translates its `transaction` field to `txHash` so X402ProxyClient.ts's contract on the
 * extension side never has to change, and maps a facilitator-side failure (bad signature,
 * expired authorization, etc.) to a 402 with `{ error: <raw facilitator reason> }`.
 * X402ProxyClient.settleX402Payment() reads that `error` field on any non-2xx response and
 * throws it verbatim (falling back to a generic status-code message only when the body isn't
 * JSON or has no `error` string) — UserFacingError.ts's x402 matchers then turn that raw reason
 * into a user-appropriate message instead of a generic "try again".
 * Stub path (default): x402Stub.ts's canned, always-succeeds data.
 */
async function handleX402Settle(request: Request, env: Env, cors: HeadersInit): Promise<Response> {
  let body: X402SettleRequestBody;
  try {
    body = parseX402SettleBody(await request.json());
  } catch (err) {
    return jsonResponse({ error: err instanceof Error ? err.message : "Invalid request body." }, 400, cors);
  }

  if (env.X402_USE_REAL_FACILITATOR === "true") {
    let result;
    try {
      result = await settleX402PaymentReal(body.resource, body.paymentPayload, env);
    } catch (err) {
      return jsonResponse({ error: err instanceof Error ? err.message : "x402 facilitator hatası." }, 502, cors);
    }
    if (!result.success) {
      return jsonResponse({ error: result.error }, 402, cors);
    }
    return jsonResponse({ success: true, txHash: result.txHash, network: result.network }, 200, cors);
  }

  return jsonResponse(buildStubSettlement(body.resource), 200, cors);
}

// ─── Worker entrypoint ──────────────────────────────────────────────

const KNOWN_PATHS = new Set([
  "/agent/chat",
  "/agent/retrieve-context",
  "/agent/x402/payment-required",
  "/agent/x402/settle",
]);

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);
    const origin = request.headers.get("Origin");
    const cors = buildCorsHeaders(origin, env);

    if (request.method === "OPTIONS") {
      // Preflight from a disallowed origin gets no CORS headers, so the browser blocks the
      // actual request itself — no need to leak a distinct error body here.
      return new Response(null, { status: cors ? 204 : 403, headers: cors ?? undefined });
    }

    if (request.method !== "POST" || !KNOWN_PATHS.has(url.pathname)) {
      return jsonResponse({ error: "Not found." }, 404, cors ?? undefined);
    }

    if (!cors) {
      return jsonResponse({ error: "Origin not allowed." }, 403);
    }

    const clientIp = request.headers.get("CF-Connecting-IP") ?? "unknown";
    const limitPerMinute = Number.parseInt(env.RATE_LIMIT_PER_MINUTE ?? "", 10) || DEFAULT_RATE_LIMIT_PER_MINUTE;
    const rate = await checkRateLimit(env.RATE_LIMIT_KV, clientIp, limitPerMinute);
    if (!rate.allowed) {
      return jsonResponse(
        { error: "Rate limit exceeded. Try again shortly." },
        429,
        { ...cors, "Retry-After": String(rate.retryAfterSeconds ?? 60) }
      );
    }

    if (url.pathname === "/agent/retrieve-context") {
      return handleRetrieveContext(request, env, cors);
    }

    if (url.pathname === "/agent/x402/payment-required") {
      return handleX402PaymentRequired(request, env, cors);
    }

    if (url.pathname === "/agent/x402/settle") {
      return handleX402Settle(request, env, cors);
    }

    if (!env.OPENROUTER_API_KEY) {
      return jsonResponse({ error: "Server misconfigured: missing OPENROUTER_API_KEY." }, 500, cors);
    }

    let body: AgentChatRequestBody;
    try {
      body = parseRequestBody(await request.json());
    } catch (err) {
      return jsonResponse({ error: err instanceof Error ? err.message : "Invalid request body." }, 400, cors);
    }

    const result = await callModelChain(body, env.OPENROUTER_API_KEY);

    switch (result.kind) {
      case "response":
        return jsonResponse(result.data, result.status, cors);
      case "all_rate_limited":
        return jsonResponse(
          {
            error: "All models in the fallback chain are currently rate limited. Try again shortly.",
            attemptedModels: result.attemptedModels,
          },
          503,
          cors
        );
      case "unreachable":
        return jsonResponse(
          {
            error: "OpenRouter is unreachable, or none of the configured models are currently available.",
            attemptedModels: result.attemptedModels,
          },
          502,
          cors
        );
    }
  },
};
